### ISSUE TITLE
Need README.md

### ISSUE THREAD

**Issue by ivanelianto** [purenaturalism/nano-electronic#1]
Need Descriptive README.md files to describe this simple websites.

**Comment by agdhruv** [comment]
@purenaturalism Hello. Very new to Open Source. Can I help with this? Could you guide me please?

**Comment by ivanelianto** [comment]
Sure! Just try to review this website first. And then describe what's is this website purpose with attractive text. 😄

**Comment by agdhruv** [comment]
Thank you. I'll work on this. Is the website hosted somewhere or do I go through the code?

**Comment by ivanelianto** [comment]
I don't host the website, so you can download or clone this repo and run it on your local computer.

**Comment by agdhruv** [comment]
Sent Pull Request. Do have a look.
