### ISSUE TITLE
Display in bigger screen

### ISSUE THREAD

**Issue by ivanelianto** [purenaturalism/nano-electronic#8]
My footer at <b>product.html</b> not keep at the bottom when the website is opened in bigger screen. Please help me to make it keep on the bottom of the screen and make main content center. Thanks

**Comment by lyzpg** [comment]
I'll give this a try in pull request #8. Let me know if it worked :)

**Comment by karczewsky** [comment]
I tried fixing what you meant in pull request #9. Hopefully it is what you meant.
